In [8]:
import pandas as pd

**Method 1: From a Dictionary**

In [9]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'San Francisco', 'London', 'Tokyo'],
    'Salary': [75000, 85000, 90000, 79000]
}

df = pd.DataFrame(data)
print(df)

      Name  Age           City  Salary
0    Alice   25       New York   75000
1      Bob   30  San Francisco   85000
2  Charlie   35         London   90000
3    David   28          Tokyo   79000

**Method 2: From a list of Lists**

In [11]:
df2 = pd.DataFrame(
    [['Alice', 25], ['Bob', 30]],
    columns = ['Name', 'age']
)

print(df2)

    Name  age
0  Alice   25
1    Bob   30

**dataframe properties**

In [13]:
print(df.shape) #nnumber of rows & columns

(4, 4)

In [14]:
print(df.columns)

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

In [16]:
print(df.dtypes)

Name      object
Age        int64
City      object
Salary     int64
dtype: object

In [17]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)

**Reading the File**

In [18]:
df = pd.read_csv('/content/user_details.csv')
print(df)

   user_id    Name  Salary  Mob_no    Address
0      101     Ram   45000  123456        USA
1      102   Shyam   56000   34521      India
2      103  Mahesh   78000  563478  Singapore
3      104  Kartik   34000   27631     Russia
4      105  Ganesh   78400  738290     Isreal
5      106   Mohan   67000   82398     France

**Read with Options**

In [23]:
df2 = pd.read_csv('/content/user_details.csv',
                 sep=',',
                 header=0,
                 usecols=['user_id','Name', 'Salary', 'Mob_no', 'Address'])
print(df2)

   user_id    Name  Salary  Mob_no    Address
0      101     Ram   45000  123456        USA
1      102   Shyam   56000   34521      India
2      103  Mahesh   78000  563478  Singapore
3      104  Kartik   34000   27631     Russia
4      105  Ganesh   78400  738290     Isreal
5      106   Mohan   67000   82398     France

**Read the file from the URL/APIs**

In [24]:
url = "https://raw.githubusercontent.com/abhishek-dataengineer/Pandas/refs/heads/main/user_details%20-%20Sheet1.csv"

df3 = pd.read_csv(url)
print(df3)

   user_id    Name  Salary  Mob_no    Address
0      101     Ram   45000  123456        USA
1      102   Shyam   56000   34521      India
2      103  Mahesh   78000  563478  Singapore
3      104  Kartik   34000   27631     Russia
4      105  Ganesh   78400  738290     Isreal
5      106   Mohan   67000   82398     France

**Explore data**

In [25]:
df3.head(4)  #Read first 4 rows

   user_id    Name  Salary  Mob_no    Address
0      101     Ram   45000  123456        USA
1      102   Shyam   56000   34521      India
2      103  Mahesh   78000  563478  Singapore
3      104  Kartik   34000   27631     Russia

In [26]:
df3.tail(3)   #Read last 3 rows

   user_id    Name  Salary  Mob_no Address
3      104  Kartik   34000   27631  Russia
4      105  Ganesh   78400  738290  Isreal
5      106   Mohan   67000   82398  France

In [27]:
df3.sample(2)  #Read some random rows

   user_id    Name  Salary  Mob_no Address
3      104  Kartik   34000   27631  Russia
1      102   Shyam   56000   34521   India

**Shape & Structure**

In [29]:
df3.shape

(6, 5)

In [30]:
df3.columns

Index(['user_id', 'Name', 'Salary', 'Mob_no', 'Address'], dtype='object')

In [31]:
df3.dtypes

user_id     int64
Name       object
Salary      int64
Mob_no      int64
Address    object
dtype: object

In [32]:
df3.info

<bound method DataFrame.info of    user_id    Name  Salary  Mob_no    Address
0      101     Ram   45000  123456        USA
1      102   Shyam   56000   34521      India
2      103  Mahesh   78000  563478  Singapore
3      104  Kartik   34000   27631     Russia
4      105  Ganesh   78400  738290     Isreal
5      106   Mohan   67000   82398     France>

**Statistical Summary**

In [33]:
df3.describe()

          user_id        Salary         Mob_no
count    6.000000      6.000000       6.000000
mean   103.500000  59733.333333  261629.000000
std      1.870829  18045.128613  308501.917232
min    101.000000  34000.000000   27631.000000
25%    102.250000  47750.000000   46490.250000
50%    103.500000  61500.000000  102927.000000
75%    104.750000  75250.000000  453472.500000
max    106.000000  78400.000000  738290.000000

In [34]:
df3.describe(include='all')

           user_id Name        Salary         Mob_no Address
count     6.000000    6      6.000000       6.000000       6
unique         NaN    6           NaN            NaN       6
top            NaN  Ram           NaN            NaN     USA
freq           NaN    1           NaN            NaN       1
mean    103.500000  NaN  59733.333333  261629.000000     NaN
std       1.870829  NaN  18045.128613  308501.917232     NaN
min     101.000000  NaN  34000.000000   27631.000000     NaN
25%     102.250000  NaN  47750.000000   46490.250000     NaN
50%     103.500000  NaN  61500.000000  102927.000000     NaN
75%     104.750000  NaN  75250.000000  453472.500000     NaN
max     106.000000  NaN  78400.000000  738290.000000     NaN

**Null Value Check**

In [36]:
df3.isnull().sum()

user_id    0
Name       0
Salary     0
Mob_no     0
Address    0
dtype: int64

In [37]:
df3.isnull().sum() / len(df3) * 100

user_id    0.0
Name       0.0
Salary     0.0
Mob_no     0.0
Address    0.0
dtype: float64

**Memory Usage**

In [38]:
df3.memory_usage(deep=True).sum()  #it'll be in the Byte

np.int64(930)